spring:
  profiles:
    active:
      - cold-box
      - prod

  application:
    name: Store
  output:
    ansi:
      enabled: always

logging:
  level:
    org.springframework: INFO
    com.castillo.pavel.store: DEBUG